<?php
# This file was automatically generated by the MediaWiki 1.25.1
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings
/*error_reporting( E_ALL );
ini_set( 'display_errors', 1 );*/
# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}

## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename = "mywiki";
$wgMetaNamespace = "Mywiki";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs
## (like /w/index.php/Page_title to /wiki/Page_title) please see:
## https://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath = "/mediawiki";
$wgScriptExtension = ".php";

## The protocol and server name to use in fully-qualified URLs
$wgServer = "http://mediawiki";

## The relative URL path to the skins directory
$wgStylePath = "$wgScriptPath/skins";
$wgResourceBasePath = $wgScriptPath;

## The relative URL path to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
$wgLogo = "$IP/images/figbooklogo-u216.png";

## UPO means: this is also a user preference option

$wgEnableEmail = true;
$wgEnableUserEmail = true; # UPO

$wgEmergencyContact = "apache@localhost";
$wgPasswordSender = "apache@localhost";

$wgEnotifUserTalk = false; # UPO
$wgEnotifWatchlist = false; # UPO
$wgEmailAuthentication = true;

## Database settings
$wgDBtype = "mysql";
$wgDBserver = "localhost";
$wgDBname = "figbookdb";
$wgDBuser = "root";
$wgDBpassword = "root";

# MySQL specific settings
$wgDBprefix = "";

# MySQL table options to use during installation or update
$wgDBTableOptions = "ENGINE=InnoDB, DEFAULT CHARSET=binary";

# Experimental charset support for MySQL 5.0.
$wgDBmysql5 = false;

## Shared memory settings
$wgMainCacheType = CACHE_NONE;
$wgMemCachedServers = array();

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads = false;
#$wgUseImageMagick = true;
#$wgImageMagickConvertCommand = "/usr/bin/convert";

# InstantCommons allows wiki to use images from http://commons.wikimedia.org
$wgUseInstantCommons = false;

## If you use ImageMagick (or any other shell command) on a
## Linux server, this will need to be set to the name of an
## available UTF-8 locale
$wgShellLocale = "en_US.utf8";

## If you want to use image uploads under safe mode,
## create the directories images/archive, images/thumb and
## images/temp, and make them all writable. Then uncomment
## this, if it's not already uncommented:
#$wgHashedUploadDirectory = false;

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publically accessible from the web.
#$wgCacheDirectory = "$IP/cache";

# Site language code, should be one of the list in ./languages/Names.php
$wgLanguageCode = "en-gb";

$wgSecretKey = "eda4c13b7cdba9c3dfb57bf4c45d78f005d14c6bd5da328dffb553db9193d48a";

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgUpgradeKey = "ec3217591567af25";

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "";
$wgRightsText = "";
$wgRightsIcon = "";

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "/usr/bin/diff3";



## Default skin: you can change the default skin. Use the internal symbolic
## names, ie 'vector', 'monobook':
$wgDefaultSkin = "apex";

# Enabled skins.
# The following skins were automatically enabled:
wfLoadSkin( 'CologneBlue' );
wfLoadSkin( 'Modern' );
wfLoadSkin( 'MonoBook' );
wfLoadSkin( 'Vector' );

require_once "$IP/skins/Metrolook/Metrolook.php";
require_once "$IP/skins/Pixeled/Pixeled.php";
require_once "$IP/skins/Dusk/Dusk.php";
require_once "$IP/skins/Bouquet/Bouquet.php"; //consider
require_once "$IP/skins/Daddio/Daddio.php";
require_once "$IP/skins/Nostalgia/Nostalgia.php";
require_once "$IP/skins/Slate/Slate.php";
require_once "$IP/skins/Schulenburg/Schulenburg.php";
require_once "$IP/skins/WPtouch/WPtouch.php";
require_once "$IP/skins/apex/apex.php";//consider
require_once "$IP/skins/erudite/erudite.php";
//require_once "$IP/skins/chameleon/Chameleon.php";
require_once "$IP/skins/Truglass/Truglass.php";//consider
require_once "$IP/skins/Synagonism/Synagonism.php";
require_once "$IP/skins/DeskMessMirrored/DeskMessMirrored.php";
require_once "$IP/skins/p2wiki/p2wiki.php";

//require_once "$IP/skins/BlueSpiceSkin/BlueSpiceSkin.php";


$wgLogo = "images/figbooklogo-u216.png";

$wgEnableApi =true;

# End of automatically generated settings.
# Add more configuration options below.
require_once("$IP/extensions/Collection/Collection.php");


$wgCollectionFormats = array(
    'rl' => 'PDF', # enabled by default
   'odf' => 'ODT',
#    'docbook' => 'DocBook XML',
#   'xhtml' => 'XHTML 1.0 Transitional',
    'epub' => 'e-book (EPUB)',
#    'zim' => 'Kiwix (OpenZIM)',
);

$wgCollectionMWServeURL = "http://localhost:8899";
$wgCollectionPODPartners = false;


$wgEnableWriteAPI = true;
$wgGroupPermissions['user']['collectionsaveasuserpage'] = true;
$wgGroupPermissions['autoconfirmed']['collectionsaveascommunitypage'] = true;






